config/routes.rb
Rails.application.routes.draw do
  resources :nbaplayers
  resources :sessions, only: [:new, :create, :destroy, :list]
  resource :lineups
  resources :lineup_items
  resources :nbaplayers do
    resources :lineup_items
  end

  post '/add_lineup_item' => 'nbaplayers#add_lineup_item'
  get '/add_pg1' => 'lineups#add_pg1'
  get '/add_pg2' => 'lineups#add_pg2'
  get '/add_sg1' => 'lineups#add_sg1'
  get '/add_sg2' => 'lineups#add_sg2'
  get '/add_sf1' => 'lineups#add_sf1'
  get '/add_sf2' => 'lineups#add_sf2'
  get '/add_pf1' => 'lineups#add_pf1'
  get '/add_pf2' => 'lineups#add_pf2'
  get '/add_c' => 'lineups#add_c'
  get '/list' => 'nbaplayers#list'
  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'
  get '/lineup' => 'lineup_items#index'

  root 'nbaplayers#list'








end

app/models/nbaplayer.rb
require 'mechanize'
require 'nokogiri'
require 'csv'
require 'json'
require 'open-uri'

class Nbaplayer < ActiveRecord::Base
  validates_presence_of :name, :position, :team, :avgpoints,:cost
  validates_numericality_of :avgpoints, greater_than: 0
  validates_uniqueness_of :name
  has_one :lineup_item
  has_one :lineup
  has_one :Nbateam

  def self.update_player
    agent = Mechanize.new { |agent| agent.user_agent_alias = "Mac Safari" }
    html = agent.get(url).body

    url = "http://www.rotowire.com/daily/nba/optimizer.htm"

    html_doc = Nokogiri::HTML(html)
    html_doc.encoding = 'utf-8'
    list = html_doc.search('//tr[starts-with(@class, "playerSe")]')
    @players = list.collect do |l|
      player = {}
      [
        [:position, 'td[5]/text()'],
        [:name, 'td[2]/a/text()'],
        [:avgpoints, 'td[8]/text()'],
        [:team, 'td[3]/text()'],
        [:cost, 'td[7]/text()']
      ].each do |name, xpath|
        player[name] = l.at_xpath(xpath).to_s.strip
      end
      self.update(:position=>player[:position],:name=>player[:name], :avgpoints=>player[:avgpoints], :team=>player[:team], :cost=>(player[:cost].tr('$','').tr(',','')).to_i, :id=>player[:id])
  end
end
end

app/controllers/nbaplayers_controller.rb
#Nbaplayers Controller
#Creates Nbaplayers and associates them?

class NbaplayersController < ApplicationController
  before_action except: [:index, :show, :home]
  before_action :set_nbaplayer, only: [:show, :edit, :update, :destroy]

  #- Scrapes data from Rotowire DFS Optimizer, storing information into Nbaplayers
  #- Displays Nbaplayers on list page
  #Need to add daily sorting?
  #Possibly migrate creation functionality to model
  def list
    @nbaplayers = Nbaplayer.where(:position=> cookies[:gposition])
    @pg1 = Nbaplayer.find_by(:id => cookies[:PG1]).name
    @pg2 = Nbaplayer.find_by(:id => cookies[:PG2]).name
    @sg1 = Nbaplayer.find_by(:id => cookies[:SG1]).name
    @sg2 = Nbaplayer.find_by(:id => cookies[:SG2]).name
    @sf1 = Nbaplayer.find_by(:id => cookies[:SF1]).name
    @sf2 = Nbaplayer.find_by(:id => cookies[:SF2]).name
    @pf1 = Nbaplayer.find_by(:id => cookies[:PF1]).name
    @pf2 = Nbaplayer.find_by(:id => cookies[:PF2]).name
    @c = Nbaplayer.find_by(:id => cookies[:C]).name
    @lineup = Nbaplayer.where(:id => LineupItem.select(:id).map(&:id))

  end
  #Creates Lineup Item for Nbaplayer identification
  def add_lineup_item
    LineupItem.create(:id => cookies[:li_id], :lineuposition => cookies[:lposition])
    cookies[cookies[:sposition].to_sym] = params[:li_id]
    redirect_to list_path
  end

  def show
  end
  # GET /nbaplayers/new
  def new
    @nbaplayer = Nbaplayer.new
  end

  def index
  end
  # GET /nbaplayers/1/edit
  def edit
  end
  # POST /nbaplayers
  # POST /nbaplayers.json
  def create
    @nbaplayer = Nbaplayer.new(nbaplayer_cookies)
    respond_to do |format|
      if @nbaplayer.save
        format.html { redirect_to list_path}
        format.json { render :show, status: :created, location: @nbaplayer }
      else
        format.html { render :new }
        format.json { render json: @nbaplayer.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /nbaplayers/1
  # PATCH/PUT /nbaplayers/1.json
  def update
    respond_to do |format|
      if @nbaplayer.update(nbaplayer_cookies)
        format.html { redirect_to @nbaplayer, notice: 'Nbaplayer was successfully updated.' }
        format.json { render :show, status: :ok, location: @nbaplayer }
      else
        format.html { render :edit }
        format.json { render json: @nbaplayer.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /nbaplayers/1
  # DELETE /nbaplayers/1.json
  def destroy
    LineupItem.destroy(cookies[:id])
    respond_to do |format|
      format.html { redirect_to list_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nbaplayer
      @nbaplayer = Nbaplayer.find(cookies[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nbaplayer_cookies
      cookies.permit(:id, :name, :position, :team, :avgpoints, :cost)
    end

end

app/helpers/nbaplayers_helper.rb
module NbaplayersHelper
  def init_position
    @@position = 'C'
  end

  def set_position(position)
    @@position = position
    format.html {redirect_to @nbaplayer }
  end
end

app/views/nbaplayers/_form.html.erb
<%= form_for(@nbaplayer) do |f| %>
  <% if @nbaplayer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nbaplayer.errors.count, "error") %> prohibited this nbaplayer from being saved:</h2>

      <ul>
      <% @nbaplayer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>s
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :avgpoints, "Average Points"%><br>
    <%= f.number_field :avgpoints %>
  </div>
  <div class="field">
    <%= f.label :cost, "Starting Lineup" %><br>
    <%= f.check_box :cost %>
  </div>
  <div class="actions">
    <%= f.submit "Create"%>
  </div>
<% end %>

app/views/nbaplayers/_pg.html.erb
<% @nbaplayers.where(:position=>'PG').each do |nbaplayer|%>
  <tr>
    <td><%= nbaplayer[:position] %></td>
    <td><%= nbaplayer[:name] %></td>
    <td><%= nbaplayer[:team]%></td>
    <td><%= nbaplayer[:avgpoints] %></td>
    <td><%= nbaplayer[:cost] %></td>
    <td><%= button_to "Add", {:controller => "lineup_items",:action=>"create", :id=>nbaplayer[:id], method: :post}%>
  </tr>
<% end %>

app/views/nbaplayers/edit.html.erb
<h3>Editing NBA Player</h3>

<%= render 'form' %>

<div class="links">
  <%= link_to 'Show', @nbaplayer %> |
  <%= link_to 'Back', nbaplayers_path %>
</div>

app/views/nbaplayers/home.html.erb
<section class="home">
  <h2>NBA Player Database</h2>
  <h3>A record of NBA Player statistics</h3>
</section>

app/views/nbaplayers/index.html.erb
<div class="userlineup">
  <p id="notice"><%= notice %></p>
  <h3>Listing NBA Players</h3>
  <table class="user-lineup-table sortable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Position</th>
        <th>Team</th>
        <th>Average Points</th>
        <th>Cost</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |nbaplayer| %>
        <tr>
          <td><%= nbaplayer[:name] %></td>
          <td><%= nbaplayer[:position] %></td>
          <td><%= nbaplayer[:team]%></td>
          <td><%= nbaplayer[:avgpoints] %></td>
          <td><%= nbaplayer[:cost] %></td>
          <td><%= button_to "+", {} %></td>
            <td><%= button_to 'Remove', nbaplayer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
        <tr>
            <td class="addmore"><%= link_to 'Add more players', list_path %></td>
        </tr>
    </tbody>
  </table>
  <br>
  <div class="graph">
    <p>Dollars per point</p>
  </div>
</div>

app/views/nbaplayers/list.html.erb
<!-- List view !-->

<div class="userlineup">
  <h3>NBA DFS Analyzer</h3>
  <p id="notice"><%= notice %></p>
  <table class="user-lineup-table sortable">
    <thead>
      <tr>
        <th>Pos</th>
        <th>Name</th>
        <th>Team</th>
        <th>Avg.</th>
        <th>Cost</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
       <tr><td class="leftmost">PG</td><td><%= @pg1 %></td><td><input type="button" onclick="window.location = '/add_pg1'" value="Add Player"></td></tr>
       <tr><td class="leftmost">PG</td><td><%= @pg2 %></td><td><input type="button" onclick="window.location = '/add_pg2'" value="Add Player"></td></tr>
       <tr><td class="leftmost">SG</td><td><%= @sg1 %></td><td><input type="button" onclick="window.location = '/add_sg1'" value="Add Player"></td></tr>
       <tr><td class="leftmost">SG</td><td><%= @sg2 %></td><td><input type="button" onclick="window.location = '/add_sg2'" value="Add Player"></td></tr>
       <tr><td class="leftmost">SF</td><td><%= @sf1 %></td><td><input type="button" onclick="window.location = '/add_sf1'" value="Add Player"></td></tr>
       <tr><td class="leftmost">SF</td><td><%= @sf2 %></td><td><input type="button" onclick="window.location = '/add_sf2'" value="Add Player"></td></tr>
       <tr><td class="leftmost">PF</td><td><%= @pf1 %></td><td><input type="button" onclick="window.location = '/add_pf1'" value="Add Player"></td></tr>
       <tr><td class="leftmost">PF</td><td><%= @pf2 %></td><td><input type="button" onclick="window.location = '/add_pf2'" value="Add Player"></td></tr>
       <tr><td class="leftmost">C</td><td><%= @c %></td><td><input type="button" onclick="window.location = '/add_c'" value="Add Player"></td></tr>
      </tr>
    </tbody>
  </table>
  <br>
</div>
<div class="userlineup">
  <p id="notice"><%= notice %></p>
  <table class="user-lineup-table sortable">
    <thead>
      <tr>
        <th>Pos</th>
        <th>Name</th>
        <th>Team</th>
        <th>Avg.</th>
        <th>Cost</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @nbaplayers.each do |player| %>
          <tr>
            <td class="leftmost"><%= player[:position] %></td>
            <td><%= player[:name] %></td>
            <td><%= player[:team]%></td>
            <td><%= player[:avgpoints] %></td>
            <td><%= number_to_currency(player[:cost]).chomp('.00') %></td>
            <td><%= button_to '+', {:action=>"add_lineup_item", :li_id => player[:id], :lposition => cookies[:sposition]}%></td>
              <td></td>
            <% end %>
          </tr>
        </tr>
    </tbody>
  </table>
</div>

app/views/nbaplayers/new.html.erb
<h3>New NBA Player</h3>

<%= render 'form' %>

<div class="links"><%= link_to 'Back', nbaplayers_path %></div>

app/views/nbaplayers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nbaplayer.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @nbaplayer.position %>
</p>

<p>
  <strong>Team:</strong>
  <%= @nbaplayer.team %>
</p>

<p>
  <strong>Avgfanduelpoints:</strong>
  <%= @nbaplayer.avgpoints %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @nbaplayer.cost%>
</p>

<div class="links">
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_nbaplayer_path(@nbaplayer) %> |
  <% end %>
  <%= link_to 'Back', list_path %>
</div>