config/routes.rb
Rails.application.routes.draw do
  resources :nbaplayers
  resources :sessions, only: [:new, :create, :destroy, :list]
  resource :lineups
  resources :lineup_items
  resources :nbaplayers do
    resources :lineup_items
  end

  post '/add_lineup_item' => 'nbaplayers#add_lineup_item'
  get '/add_pg1' => 'lineups#add_pg1'
  get '/add_pg2' => 'lineups#add_pg2'
  get '/add_sg1' => 'lineups#add_sg1'
  get '/add_sg2' => 'lineups#add_sg2'
  get '/add_sf1' => 'lineups#add_sf1'
  get '/add_sf2' => 'lineups#add_sf2'
  get '/add_pf1' => 'lineups#add_pf1'
  get '/add_pf2' => 'lineups#add_pf2'
  get '/add_c' => 'lineups#add_c'
  get '/list' => 'nbaplayers#list'
  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'
  get '/lineup' => 'lineup_items#index'

  root 'nbaplayers#list'








end

app/models/lineup.rb
class Lineup < ActiveRecord::Base
  validates_presence_of :pg1,:pg2,:sg1,:sg2,:sf1,:sf2,:pf1,:pf2,:center
  belongs_to :line_up_status
  has_many :lineup_items
  has_many :nbaplayers
  before_create :set_lineup_status
  before_save :update_total

  def total
    lineup_items.collect{ |oi| oi.valid? ? (oi.quantity*oi.cost) : 0}.sum
  end


private
  def set_lineup_status
    self.lineup_status_id = 1
  end
  def update_total
    self[:total] = total
  end
end

app/controllers/lineups_controller.rb
class LineupsController < ApplicationController
  def show
    @lineup_items = current_lineup.lineup_items
  end

  def add_pg1
    cookies[:sposition] = "PG1"
    cookies[:gposition] = "PG"

    redirect_to root_url
  end

  def add_pg2
    cookies[:sposition] = "PG2"
    cookies[:gposition] = "PG"

    redirect_to root_url
  end

  def add_sg1
    cookies[:sposition] = "SG1"
    cookies[:gposition] = "SG"

    redirect_to root_url
  end

  def add_sg2
    cookies[:sposition] = "SG2"
    cookies[:gposition] = "SG"

    redirect_to root_url
  end

  def add_sf1
    cookies[:sposition] = "SF1"
    cookies[:gposition] = "SF"

    redirect_to root_url
  end

  def add_sf2
    cookies[:sposition] = "SF2"
    cookies[:gposition] = "SF"

    redirect_to root_url
  end

  def add_pf1
    cookies[:sposition] = "PF1"
    cookies[:gposition] = "PF"

    redirect_to root_url
  end

  def add_pf2
    cookies[:sposition] = "PF2"
    cookies[:gposition] = "PF"

    redirect_to root_url
  end

  def add_c
    cookies[:sposition] = "C"
    cookies[:gposition] = "C"

    redirect_to root_url
  end
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/views/lineups/_lineup.html.erb
<% if !@lineup_item.nil? && @lineup_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @lineup_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @lineup_items.size == 0 %>
  <p class="text-center">
    No Players. Please <%= link_to "go back", root_path %> and add players.
  </p>
<% else %>
<table>
<tbody>
    <% @lineup_items.each do |lineup_item| %>
    <tr>
    <td><%= lineup_item[:position] %></td>
    <td><%= lineup_item[:name] %></td>
    <td><%= lineup_item[:team]%></td>
    <td><%= lineup_[:avgpoints] %></td>
    <td><%= [:cost] %></td>
    <td><%= button_to "Add", {:controller => lineup_items_path, :action=>"create", :id=>[:id], :position=>[:position], :team =>[:team], :avgpoints =>[:avgpoints], :cost=>[:cost], method: :post }%>
    </tr>
    <% end %>
  </tr>
  </tbody>
  </table
<% end %>

app/views/lineups/_lineup_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= nbaplayer.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for lineup_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency lineup_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: lineup_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :id, value: nbaplayer.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", lineup_item, { data: { confirm: "Are you sure you wish to delete the product '#{lineup_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency lineup_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/lineups/show.html.erb
<div class="lineup">
  <%= render "lineup" %>
</div>