config/routes.rb
Rails.application.routes.draw do
  resources :nbaplayers
  resources :sessions, only: [:new, :create, :destroy, :list]
  resource :lineups
  resources :lineup_items
  resources :nbaplayers do
    resources :lineup_items
  end

  post '/add_lineup_item' => 'nbaplayers#add_lineup_item'
  get '/add_pg1' => 'lineups#add_pg1'
  get '/add_pg2' => 'lineups#add_pg2'
  get '/add_sg1' => 'lineups#add_sg1'
  get '/add_sg2' => 'lineups#add_sg2'
  get '/add_sf1' => 'lineups#add_sf1'
  get '/add_sf2' => 'lineups#add_sf2'
  get '/add_pf1' => 'lineups#add_pf1'
  get '/add_pf2' => 'lineups#add_pf2'
  get '/add_c' => 'lineups#add_c'
  get '/list' => 'nbaplayers#list'
  get '/sign-in' => 'sessions#new'
  delete '/sign-out' => 'sessions#destroy'
  get '/lineup' => 'lineup_items#index'

  root 'nbaplayers#list'








end

app/views/layouts/_lineup_text.html.erb
<%= link_to "#{current_lineup.lineup_items.size} Items in Cart ( #{number_to_currency current_lineup.total} )", lineup_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NBA Player Database</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://code.jquery.com/jquery-2.1.3.min.js"</script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="/assets"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="content">
    <% flash.each do |type, message| %>
      <div class="<%= type %>">
        <p><%= message %></p>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>